[build]
  # This ensures your static files (HTML, CSS) are published from the root
  publish = "/"
  
# This is the essential part that tells Netlify where to find the Python code
[functions]
  directory = "netlify-functions"

[[redirects]]
  from = "/api/generate-roadmap"
  to = "/.netlify/functions/generate-roadmap"
  status = 200
