[build]
  # This simple command is necessary to kickstart the build process
  command = "echo 'Build Complete'" 
  publish = "/"

[functions]
  # This tells Netlify where to find the Python code
  directory = "netlify-functions"

[[redirects]]
  from = "/api/generate-roadmap"
  to = "/.netlify/functions/generate-roadmap"
  status = 200
