[build]
  command = "echo 'Build Complete'" 
  publish = "/" 
  
[functions]
  directory = "netlify-functions"

[[redirects]]
  from = "/api/generate-roadmap"
  to = "/.netlify/functions/generate-roadmap"
  status = 200
