[build]
  # This is the new line. It forces the Python build environment to execute.
  command = "echo 'Netlify build complete'" 
  publish = "/"
  
[functions]
  # This confirms the folder where Netlify looks for your Python function
  directory = "netlify-functions"

[[redirects]]
  from = "/api/generate-roadmap"
  to = "/.netlify/functions/generate-roadmap"
  status = 200
